#######
# Compiled from data/dawn/functions/load.mcscript
# to .//data/dawn/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######

# Extended from data/dawn/functions/main.mcscript
# to data/dawn/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add tmp dummy
